language: python

python:
    - "3.4"
    - "3.5"

cache:
  directories:
    - $HOME/.cache/pip

install:
    - pip install -r requirements-test.txt

script: 
    - py.test tests.py

services:
  - mongodb
